version: "3"

services:
  postgres:
    image: "postgres:9.5"
    
    environment:
      #- POSTGRES_DB=tadpgweb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ=GMT
    volumes:
      - "postgres:/var/lib/postgresql/data"
    ports:
      - 5432:5432
  app:
    depends_on:
      - "postgres"
    build: .
    command: bash start.sh
    ports:
      - "3000:3000"
    volumes:
      - .:/onebitexchange
      - gems:/gems
 

volumes:
  postgres:
  gems: